### ISSUE TITLE
Unpin or delete this repo

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterAppsFreezer/InvoiceDemo#74]
This repo is one of the first things that people see when they go to github/starcounter since it's pinned. The InvoiceDemo is outdated and has been completely replaced by the HelloWorld tutorial. Because of this I suggest that the repo is either deleted or unpinned to not cause any confusion for people that go to this page.

@warpech

**Comment by warpech** [comment]
Unpinning, moving to StarcounterAppFreezer.

**Comment by warpech** [comment]
Done

**Comment by warpech** [comment]
@Mackiovello could you pls go through all of these issues in this repo and check if they should be tracked in TechComm or HelloWorld? I think some might still make sense.

**Comment by Mackiovello** [comment]
Yes, I'll take care of that
